# Config file for automatic testing at travis-ci.org

language: python
python: 3.7
dist: xenial
sudo: true

install: pip install -U pip tox
script: tox

matrix:
  fast_finish: true
  include:
    - name: Python 2.7
      python: 2.7
      env: TOXENV=py27

    - name: Python 3.5
      python: 3.5
      env: TOXENV=py35

    - name: Python 3.6
      python: 3.6
      env: TOXENV=py36

    - name: Python 3.7
      python: 3.7
      env: TOXENV=py37

    - name: Dependency vulnerability checks
      env: TOXENV=safety

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: GoodRx
  password:
    secure: "SlifMs2WrvWswE9APuZGc1jF8wOgV73BHH50yiH3F+5ADPgOhKJRzwHfjJcgAtIjfc/q6p3+sjsCBwz82FzBMXsD7MPiogQvYdHlPFeu2R/vIzgHcTsFSnva0y+9P5juc7mFDPRCcLGXnw103MdrumZwxdUGqAS7VyW/9qfCOuUlxphhk14R0tnG3Nof5hZh0vRKO1v0pDwDnR6e+2R3sh7Yl5+vtRhLALPnjDgZpubUbJCq3bFVog4vywdqOZ2fBGWaJEt22DPLLwWpTghakTNHPnOKJvNYDR9Y+N5Hx4sye4ECdQtbeoCY3ONc3fya3Il2Q2ndWiumN6wOd8K+N4T4rHHKWOTwiMY+oAFEYQPAQdFmGPoVG3Wl0Z96VhV4iEgo1Nu8soRNnWOtZOFVQmnvs+Z+D/LSKqFeaXbHyG2kflKyghUIpHEIFcDYt6y3H55XDXj0Dr/VxbJddfTC+HDWr+5N9tj2Dn+2PEEgn/IL0tYJnzwuy8Rv0cPMJXIizjnGTyXFhmlYdW2JPxdqSraaTd1KWjdOA54L7fNJibE6v0MsXOyi9xTyYJBzXdK8PtPxdYFpec2cuUSRRrS8/lh5pX4O2MhRi41P58cQkDEf75Q7A5cApwILooMp5fH+xHBg8LOeE3KifA9kEe1g/KT75M93ghPmwUA5PKwkCt4="
  on:
    tags: true
    repo: GoodRx/pyramid-sendgrid-webhooks
    condition: $TOXENV == py27

branches:
  only:
    - master
    # Match tags starting with "vN..."
    - /^v\d+.*$/
