# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.7
dist: xenial
sudo: true

install: pip install -U pip tox
script: tox

matrix:
  fast_finish: true
  include:
    - name: Python 2.7
      python: 2.7
      env: TOXENV=py27

    - name: Python 3.5
      python: 3.5
      env: TOXENV=py35

    - name: Python 3.6
      python: 3.6
      env: TOXENV=py36

    - name: Python 3.7
      python: 3.7
      env: TOXENV=py37

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: GoodRx
  password:
    secure: LC9HIDopqJSLhxkCEJ4Wlr4vxBUiEOXH5+O5YIHFDn07gB01mALMPktOH7ujDkYl3Ct9301FMvxnbEd72O7oxzdaokuhJDCb2VtiECObaVAAB5GyNB4IZE0/TYRVfv/OHXlvL8YWxDnWpCa70mccHgB0N91pGsjrB+3gWDiek3C/e9bENXCdohtBLOH4RERXvSpx+iVynDpeKXFzg3kNezQMHDIGZN39qT4o2+4AXjYlzLQc5nnTOm4L9BPzT7oV1MV33TRdL1L1z98zKm/vRkLwrE6Du+Sn4LBYubm6b9nWywZ3wCNmp30B7Deslbl+NzC14IJlXER4pvEqTuTg6I0jEiDBASAtv1QyYB/X0JhOudP5vXcRJ7sgyoTvtfX3ufcJ/OADD/SrpWz6YecHUCzTq9EMmCtX+kPWVIafTsTWbtaJU+pe+Q7QDMDLYBz5VntnxH/HN6xQJw9IrrvfzLwmCDSUUkI78Ot1eBgFJjvT0Nvc4vni9sD1LFRE8dUaFLAI541gr3rWx8Tw3mCkH6r8KPZfDGIHWcccNKiWbfKkwVb9fSet0t2nyAuNhh0jJ3gJe4NQbi7WChwNidHp/Cr0mI0dhR94Jdu66nZ2V39x/j4YHa8DqRunRbVB5n0OjBb1eJXbEThrLd7tP5rGxnDOazQqjta2VxrWzNqo46c=
  on:
    tags: true
    repo: GoodRx/pyramid-sendgrid-webhooks
    condition: $TOXENV == py27
